# Ballerina demo config file
clientId = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
clientSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
accessToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
accessTokenSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"