# Ballerina demo config file
clientId = "XXXXXXXXXXXXXXXXXXX"
clientSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
accessToken = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
accessTokenSecret = "XXXXXXXXXXXXXXXXXXXXXXXXXXX"
